name: "Test pr"

on: 
  pull_request:
    types: 
      - opened

jobs:
  add-pr-to-ecosystem-events-review-board:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: 'Add PR to Ecosystem Events Review Board - Ready For Review'
      uses: actions/add-to-project@v0.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        project-url: "https://github.com/users/yxnyxnyxnyxnyxnyxn/projects/1"
